#!/usr/bin/env guile
!#
;;; copyinorder --- Copy files in alphabetical order

;; Copyright © 2026 Alex Kost

;; Author: Alex Kost <alezost@gmail.com>
;; Created: 8 Mar 2026

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

(use-modules
 (srfi srfi-26)
 (srfi srfi-37)
 (al let-macros)
 (al utils)
 (al files)
 (al messages))

(define %regexp "\\.mp3$")

(define (show-help)
  (format #t "Usage: ~a [OPTIONS ...] SOURCE DESTINATION"
          (car (command-line)))
  (display "
Copy file(s) from SOURCE to DESTINATION in alphabetical order.

Arguments:
  SOURCE            what to copy (directory)
  DESTINATION       where to copy (directory)

Options:
  -h, --help        display this help and exit

  -r VALUE, --regexp=VALUE
        Copy only files matching VALUE regular expression.")
  (format #t "
        Default: \"~a\".~%" %regexp)
  (display "
  -R VALUE, --recursive=VALUE
        If \"y\"/\"yes\" (default), copy files from SOURCE recursively.
        If \"n\"/\"no\", do not copy SOURCE sub-directories.")
  (newline))

(define %options
  (list
   (option '(#\h "help") #f #f
           (lambda _
             (show-help)
             (exit 0)))
   (option '(#\r "regexp") #t #f
           (lambda (opt name arg seed)
             (assq-set! seed 'regexp arg)))
   (option '(#\R "recursive") #t #f
           (lambda (opt name arg seed)
             (assq-set! seed 'recursive? (string->bool arg))))))

(define (parse-args args)
  "Return alist of options from command-line ARGS."
  (args-fold
   args %options
   (lambda (opt name arg seed)
     (print-error "Unrecognized option: \"~a\"." name)
     seed)
   (lambda (arg seed)
     (if (assq 'destination seed)
       (begin
         (print-error "Too many positional arguments.
Ignoring everything after DESTINATION.")
         seed)
       (if (assq 'source seed)
         (acons 'destination arg seed)
         (acons 'source arg seed))))
   (list (cons 'recursive? #t)
         (cons 'regexp %regexp))))

(define* (copy-source source destination
                      #:key recursive? regexp)
  "Copy files from SOURCE directory to DESTINATION directory."
  (unless (and (file-exists? source)
               (file-is-directory? source))
    (leave "Source directory does not exist: ~a" source))

  (let* ((destination (build-file-name destination (basename source)))
         (source      (canonicalize-file-name source))
         (full-names  (find-files source regexp
                                  #:enter-tree? recursive?
                                  #:follow-links? #t)))
    (if (null? full-names)
      (begin
        (print-output "No matching files found in \"~a\"." source)
        (exit 0))
      (let* ((total         (length full-names))
             (source-length (string-length source))
             (rel-names     (map (lambda (name)
                                   (substring name (1+ source-length)))
                                 full-names))
             (rel-names     (sort rel-names string<)))
        (for-each-indexed
         (lambda (i name)
           (let ((old-name (build-file-name source      name))
                 (new-name (build-file-name destination name)))
             (print-output "[~2d of ~d] ~a" i total new-name)
             (copy-file* old-name new-name)))
         rel-names)))))

(define (main arg0 . args)
  (if-let ((opts        (parse-args args))
           (source      (assq-ref opts 'source))
           (destination (assq-ref opts 'destination)))
    (copy-source source destination
                 #:recursive? (assq-ref opts 'recursive?)
                 #:regexp (make-regexp (assq-ref opts 'regexp)
                                       regexp/icase))
    (leave "SOURCE and DESTINATION should be specified.
See \"~a --help\" for more information" arg0)))

(when (batch-mode?)
  (apply main (command-line)))

;;; copyinorder ends here
